server:
  port: 0
spring:
  application:
    name: product-service
  cache:
    cache-names: products
  profiles:
    active: production
  instance:
    # enable to register multiple app instances with a random server port
    instance-id: ${spring.application.name}:${random.uuid}
  datasource:
    url: jdbc:mysql://localhost:3306/micropos
    username: root
    password: wxyv@0.

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
debug: true