server:
  port: 80 #端口号

spring:
  application:
    name: micropos-gateway  #服务注册中心注册的服务名

  cloud:
    gateway: #网关路由配置
      discovery:
        locator:
          enabled: true #默认值为 true，即默认开启从注册中心动态创建路由的功能，利用微服务名进行路

      routes:
        #将 micro-service-cloud-provider-dept-8001 提供的服务隐藏起来，不暴露给客户端，只给客户端暴露 API 网关的地址 9527
        - id: products-service_route   #路由 id,没有固定规则，但唯一，建议与服务名对应
          uri: lb://product-service #动态路由，使用服务名代替上面的具体带端口   http://eureka7001.com:9527/dept/list

          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/api/product/**    #断言，路径匹配 注意：Path 中 P 为大写
            - Method=GET #只能时 GET 请求时，才能访问

        - id: cart-service_route
          uri: lb://cart-service

          predicates:
            #以下是断言条件，必选全部符合条件
            - Path=/api/item/**    #断言，路径匹配 注意：Path 中 P 为大写
            - Method=[GET, PUT, POST, DELETE] #只能时 GET 请求时，才能访问

        - id: check-service-route
          uri: lb://check-server
          predicates:
           - Path=/api/check/**
           - Method=[GET]
        - id: delivery-service-route
          uri: lb://delivery-service
          predicates:
            - Path=/api/delivery/**
            - Method=[GET]

eureka:
  instance:
    instance-id: micro-service-cloud-gateway
    hostname: micro-service-cloud-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/